#!/usr/bin/env bash
# Prints the string 'To infinity and beyond' indefinitely and handles the SIGTERM signal

trap "echo I am invincible!!!" 15

while true
do
	echo "To infinity and beyond"
	sleep 2
done
