#!/usr/bin/env bash
# This script will display "Best School" 10 times using a while loop
# On the 9th iteration, "Best School" and "Hi" will be displayed on separate lines

count=1
while [ $count -le 10 ]; 
do
    if [ $count -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    count=$((count+1))
done

